// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXYRPm9y2d5a3oY4A180pp2b2VXtYSUSk',
    appId: '1:57006891258:web:a28148af5e62ed2921e943',
    messagingSenderId: '57006891258',
    projectId: 'fir-f230b',
    authDomain: 'fir-f230b.firebaseapp.com',
    storageBucket: 'fir-f230b.firebasestorage.app',
    measurementId: 'G-H2N1DG7341',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJvr-5NizdPtp24SVZiaIGkO94X2AWcik',
    appId: '1:57006891258:android:9be79f90a59d98fb21e943',
    messagingSenderId: '57006891258',
    projectId: 'fir-f230b',
    storageBucket: 'fir-f230b.firebasestorage.app',
  );
}
